"""
Configuration loading for commit-guard.

Settings are resolved in order of increasing precedence:

1. built-in defaults
2. ``[tool.commit-guard]`` in ``pyproject.toml``
3. ``.commit-guard.toml`` (whole file, or a ``[commit-guard]`` table)
4. explicit command-line flags

Discovery walks upwards from the starting directory to the repository root, so
running ``git commit`` in a subdirectory picks up the project configuration.
Unknown keys are reported as errors rather than ignored, so that a typo such as
``max_header_length`` does not silently leave the default in place.
"""

import os
from typing import Any, Dict, List, Optional, Sequence, Set

from commit_guard._toml import TomlError, loads

__all__ = ["Config", "ConfigError", "load_config", "find_config_files"]

CONFIG_FILENAME = ".commit-guard.toml"
PYPROJECT_FILENAME = "pyproject.toml"
TOOL_TABLE = "commit-guard"


class ConfigError(Exception):
    """Raised when a configuration file is malformed or has invalid values."""


# Conventional Commit types recognised unless configuration overrides them.
DEFAULT_TYPES = (
    "feat",
    "fix",
    "docs",
    "style",
    "refactor",
    "perf",
    "test",
    "build",
    "ci",
    "chore",
    "revert",
)

# Filename patterns that should never be committed. These are regexes matched
# against the forward-slash-normalised path.
DEFAULT_SENSITIVE_PATTERNS = (
    r"(^|/)\.env($|\..*)",
    r"(^|/).*\.(pem|pkcs12|pfx|p12|jks|keystore)$",
    r"(^|/)id_(rsa|dsa|ed25519|ecdsa)($|\..*)",
    r"(^|/).*(secret|password|credential)s?.*\.(json|ya?ml|txt|ini|cfg)$",
    r"(^|/)\.(npmrc|pypirc|netrc)$",
    r"(^|/)\.aws/credentials$",
    r"(^|/).*\.key$",
)

# Paths excluded from sensitive-name matching by default. Sample and template
# files are published deliberately, and ``*.key`` has enough innocent uses that
# shipping these keeps the first run from being all false positives.
DEFAULT_ALLOWLIST = (
    "*.example",
    "*.sample",
    "*.template",
    "*.dist",
    ".env.example",
    ".env.sample",
    ".env.template",
)

# Commit subjects starting with any of these are generated by git itself or by
# an interactive rebase, and are not the author's to format.
DEFAULT_SKIP_PREFIXES = (
    "merge ",
    "revert ",
    "fixup!",
    "squash!",
    "amend!",
)

_BOOL_KEYS = (
    "require_scope",
    "allow_trailing_period",
    "skip_merge_commits",
)
_INT_KEYS = (
    "max_header_len",
    "max_body_line_len",
    "subject_min_len",
)
_FLOAT_KEYS = ("max_size_mb",)
_LIST_KEYS = (
    "types",
    "scopes",
    "sensitive_patterns",
    "extra_sensitive_patterns",
    "allowlist",
    "skip_prefixes",
)

KNOWN_KEYS = frozenset(_BOOL_KEYS + _INT_KEYS + _FLOAT_KEYS + _LIST_KEYS)


class Config:
    """Resolved commit-guard settings."""

    __slots__ = (
        "types",
        "scopes",
        "require_scope",
        "max_header_len",
        "max_body_line_len",
        "subject_min_len",
        "allow_trailing_period",
        "max_size_mb",
        "sensitive_patterns",
        "allowlist",
        "skip_merge_commits",
        "skip_prefixes",
        "sources",
    )

    def __init__(
        self,
        types: Sequence[str] = DEFAULT_TYPES,
        scopes: Sequence[str] = (),
        require_scope: bool = False,
        max_header_len: int = 72,
        max_body_line_len: int = 0,
        subject_min_len: int = 3,
        allow_trailing_period: bool = False,
        max_size_mb: float = 10.0,
        sensitive_patterns: Sequence[str] = DEFAULT_SENSITIVE_PATTERNS,
        allowlist: Sequence[str] = DEFAULT_ALLOWLIST,
        skip_merge_commits: bool = True,
        skip_prefixes: Sequence[str] = DEFAULT_SKIP_PREFIXES,
        sources: Sequence[str] = (),
    ) -> None:
        self.types: Set[str] = set(types)
        self.scopes: Set[str] = set(scopes)
        self.require_scope = require_scope
        self.max_header_len = max_header_len
        # 0 disables the body line-length check.
        self.max_body_line_len = max_body_line_len
        self.subject_min_len = subject_min_len
        self.allow_trailing_period = allow_trailing_period
        self.max_size_mb = max_size_mb
        self.sensitive_patterns: List[str] = list(sensitive_patterns)
        self.allowlist: List[str] = list(allowlist)
        self.skip_merge_commits = skip_merge_commits
        self.skip_prefixes: List[str] = [p.lower() for p in skip_prefixes]
        self.sources: List[str] = list(sources)

    def __repr__(self) -> str:
        return "Config(types={0}, max_header_len={1}, sources={2})".format(
            sorted(self.types), self.max_header_len, self.sources
        )


def find_config_files(start_dir: Optional[str] = None) -> List[str]:
    """
    Locate configuration files, nearest-last so later files win.

    Walks upward from ``start_dir`` to the filesystem root, stopping after the
    directory that contains ``.git``. Returns absolute paths.
    """
    base = os.path.abspath(start_dir or os.getcwd())
    chain: List[str] = []

    current = base
    while True:
        chain.append(current)
        if os.path.exists(os.path.join(current, ".git")):
            break
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent

    found: List[str] = []
    # Reversed so the outermost directory is processed first and the nearest
    # configuration file ends up last in the list.
    for directory in reversed(chain):
        for name in (PYPROJECT_FILENAME, CONFIG_FILENAME):
            candidate = os.path.join(directory, name)
            if os.path.isfile(candidate):
                found.append(candidate)
    return found


def _extract_table(data: Dict[str, Any], path: str) -> Optional[Dict[str, Any]]:
    """
    Pull the commit-guard settings table out of one parsed file.

    ``pyproject.toml`` must use ``[tool.commit-guard]``. A dedicated
    ``.commit-guard.toml`` may either use a ``[commit-guard]`` table or place
    settings at the top level.
    """
    if os.path.basename(path) == PYPROJECT_FILENAME:
        tool = data.get("tool")
        if not isinstance(tool, dict):
            return None
        section = tool.get(TOOL_TABLE)
        if section is None:
            return None
        if not isinstance(section, dict):
            raise ConfigError(
                "{0}: [tool.{1}] must be a table".format(path, TOOL_TABLE)
            )
        return section

    section = data.get(TOOL_TABLE)
    if isinstance(section, dict):
        return section
    # Top-level settings; drop nested tables so a stray [tool] block in a
    # standalone config file does not look like a setting.
    return {k: v for k, v in data.items() if not isinstance(v, dict)}


def _coerce(path: str, key: str, value: Any) -> Any:
    """Validate one setting's type, raising ConfigError with the file name."""
    where = "{0}: '{1}'".format(path, key)

    if key in _BOOL_KEYS:
        if not isinstance(value, bool):
            raise ConfigError("{0} must be true or false".format(where))
        return value

    if key in _INT_KEYS:
        # bool is a subclass of int; reject it explicitly.
        if isinstance(value, bool) or not isinstance(value, int):
            raise ConfigError("{0} must be an integer".format(where))
        if value < 0:
            raise ConfigError("{0} must not be negative".format(where))
        return value

    if key in _FLOAT_KEYS:
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ConfigError("{0} must be a number".format(where))
        if value <= 0:
            raise ConfigError("{0} must be greater than zero".format(where))
        return float(value)

    if key in _LIST_KEYS:
        if not isinstance(value, list) or not all(
            isinstance(item, str) for item in value
        ):
            raise ConfigError("{0} must be a list of strings".format(where))
        return list(value)

    raise ConfigError(
        "{0} is not a recognised setting. Valid keys: {1}".format(
            where, ", ".join(sorted(KNOWN_KEYS))
        )
    )


def _apply(config: Config, path: str, section: Dict[str, Any]) -> None:
    """Merge one settings table onto an existing Config in place."""
    values: Dict[str, Any] = {}
    for key, raw in section.items():
        values[key] = _coerce(path, key, raw)

    if "types" in values:
        if not values["types"]:
            raise ConfigError("{0}: 'types' must not be empty".format(path))
        config.types = set(values["types"])
    if "scopes" in values:
        config.scopes = set(values["scopes"])
    if "sensitive_patterns" in values:
        config.sensitive_patterns = list(values["sensitive_patterns"])
    # extra_sensitive_patterns adds to whatever is in effect, so a project can
    # extend the defaults without restating them.
    if "extra_sensitive_patterns" in values:
        config.sensitive_patterns = config.sensitive_patterns + list(
            values["extra_sensitive_patterns"]
        )
    if "allowlist" in values:
        config.allowlist = list(values["allowlist"])
    if "skip_prefixes" in values:
        config.skip_prefixes = [p.lower() for p in values["skip_prefixes"]]

    for key in _BOOL_KEYS + _INT_KEYS + _FLOAT_KEYS:
        if key in values:
            setattr(config, key, values[key])

    if config.require_scope and not config.scopes:
        raise ConfigError(
            "{0}: 'require_scope' is set but 'scopes' is empty".format(path)
        )

    config.sources.append(path)


def load_config(
    start_dir: Optional[str] = None,
    config_path: Optional[str] = None,
    use_files: bool = True,
) -> Config:
    """
    Build a Config from discovered files.

    ``config_path`` names a single file explicitly and disables discovery; a
    missing file is an error in that case, since the user asked for it by name.
    ``use_files=False`` returns the built-in defaults, for ``--no-config``.
    """
    config = Config()
    if not use_files:
        return config

    if config_path:
        if not os.path.isfile(config_path):
            raise ConfigError("configuration file not found: {0}".format(config_path))
        paths = [os.path.abspath(config_path)]
    else:
        paths = find_config_files(start_dir)

    for path in paths:
        try:
            with open(path, encoding="utf-8") as handle:
                text = handle.read()
        except OSError as exc:
            raise ConfigError("cannot read {0}: {1}".format(path, exc)) from exc

        try:
            data = loads(text)
        except TomlError as exc:
            # A broken pyproject.toml is somebody else's problem unless the user
            # pointed us at it; skipping keeps commit-guard usable meanwhile.
            if os.path.basename(path) == PYPROJECT_FILENAME and not config_path:
                continue
            raise ConfigError("cannot parse {0}: {1}".format(path, exc)) from exc

        section = _extract_table(data, path)
        if section:
            _apply(config, path, section)

    return config
